[2024-06-28T12:19:44.147+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T12:19:44.459+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.train_model manual__2024-06-28T08:50:28.278961+00:00 [queued]>
[2024-06-28T12:19:44.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.train_model manual__2024-06-28T08:50:28.278961+00:00 [queued]>
[2024-06-28T12:19:44.490+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-28T12:19:44.541+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_model> on 2024-06-28 08:50:28.278961+00:00
[2024-06-28T12:19:44.591+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=65) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T12:19:44.622+0000] {standard_task_runner.py:63} INFO - Started process 78 to run task
[2024-06-28T12:19:44.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'train_model', 'manual__2024-06-28T08:50:28.278961+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpchp6142w']
[2024-06-28T12:19:44.624+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask train_model
[2024-06-28T12:19:44.869+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.train_model manual__2024-06-28T08:50:28.278961+00:00 [running]> on host 52971778f83a
[2024-06-28T12:19:45.516+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T08:50:28.278961+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T08:50:28.278961+00:00'
[2024-06-28T12:19:45.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T12:19:45.687+0000] {warnings.py:112} WARNING - /opt/***/scripts/train_model.py:16: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['temperature_2m'].fillna(method='ffill', inplace=True)

[2024-06-28T12:19:45.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T12:19:45.744+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/train_model.py", line 35, in train_model
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 2778, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_split.py", line 2408, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.
[2024-06-28T12:19:45.815+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=train_model, run_id=manual__2024-06-28T08:50:28.278961+00:00, execution_date=20240628T085028, start_date=20240628T121944, end_date=20240628T121945
[2024-06-28T12:19:45.898+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task train_model (With n_samples=0, test_size=0.2 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.; 78)
[2024-06-28T12:19:45.978+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T12:19:46.059+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T12:19:46.068+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
